name: Trident
main: TheNote\PMTrident\Main
version: 2.0.2
api:
  - 5.0.0
author: TheNote
authors:
  #Thanks to the old Code!
  - CortexPE
  #Updated to PM5
  - Terpz710
description: Add Trident
